### ISSUE TITLE
Your Code installation appears to be corrupt. Please reinstall.

### ISSUE THREAD

**Issue by TTPw1nd** [spikespaz/vscode-smoothtype#3]
I get that error after install the extension.
MacOS High Sierra 10.13.5
VSCode 1.24.0

**Comment by spikespaz** [comment]
This is the result of the extension modifying the index file, it injects necessary CSS (safely I assure you) so the editor recognizes that it has been compromised. This will not effect the functionality of the editor outside of the scope of the extension.

I will add a notice to the README file explaining this.
For now, the best thing you can do is click the cog on that notification, and click "Don't show again".

I'm not sure if "Don't show again" is exactly what it says. Could you please let me know what it actually is?

**Comment by santunu23** [comment]
In my case the html files modified automatically,every time I open the html files,there are a big amount of data add automatically.Is this for any extension I installed?

![image](https://user-images.githubusercontent.com/20766337/56297870-fc52ad00-6152-11e9-9ded-e4501afb4fcc.png)
![image](https://user-images.githubusercontent.com/20766337/56297893-070d4200-6153-11e9-9935-5784e6f25e6e.png)
![image](https://user-images.githubusercontent.com/20766337/56297946-1be9d580-6153-11e9-9af6-80ef48cad7be.png)

**Comment by spikespaz** [comment]
This is definitely not something that SmoothType wrote. I suggest taking a look at other extensions that may write to Code's `index.html`, such as icon packs for the explorer. In older versions, SmoothType wrote to this file, but now it just changes `workbench.main.css`.

If this extension has written to the file it will look like below.

![image](https://user-images.githubusercontent.com/12502988/56301342-79970700-60ec-11e9-9a04-7c4916320c25.png)

**Comment by spikespaz** [comment]
@santunu23

**Comment by santunu23** [comment]
Hi spikespaz, thank you  there are lots of extension installed on my visual code platform,have to find which one damage.

**Comment by aniforprez** [comment]
Hey why does this continue to happen when the extension is uninstalled? How do I make this go away?

**Comment by aniforprez** [comment]
All right so apparently to stop this you need to "Disable" smooth scroll with the extension installed and then uninstall the extension. @spikespaz if possible please add this also to the README

**Comment by spikespaz** [comment]
@aniforprez I agree that it should be in the README. This extension is deprecated anyway (because its primary feature was mercilessly cored) unless you wish to fine-tune the animation (which isn't available in the built-in settings).

If the issue was the appended `[Unsupported]` in the titlebar, you could have used [my fork of an extension that fixes this issue](https://github.com/spikespaz-forks/vscode-fix-checksums). There's a VSIX file in the root of that repository.

But alas this extension is (mostly) pointless now. ¯\\\_(ツ)_/¯

**Comment by aniforprez** [comment]
Thank you!

**Comment by angelhdzmultimedia** [comment]
### [FEATURE REQUEST]

Maybe adding a "Reinstall" button when that corruption message is displayed...

**Comment by spikespaz** [comment]
@angelhdz The corruption message shows that VS Code is corrupted because this extension changes core files of the editor. A reinstall button wouldn't help no matter what it re-installs, the extension isn't broken in the first place, and reinstalling VSC would undo changes made by SmoothType.

Please use the new `editor.cursorSmoothCaretAnimation` option in your user settings; the primary and only feature of this extension has been cored. The only thing that VSC cannot do is change the animation duration, this extension can.

If this is why you require the extension, my only further advice is to use the solutions already given for solving this problem (namely my fork of another extension).

**If you do not require customization of the animation duration, uninstall the extension and use the setting built into VSC.**

### Please consult the [readme](../blob/master/README.md) for more information.
